plugins {
    id 'com.android.application'
}

android {
    namespace 'com.k2040.geojoystick'
    compileSdk 36
    buildToolsVersion '35.0.0'

    defaultConfig {
        applicationId 'com.k2040.geojoystick'
        minSdk 27
        targetSdk 36
        versionCode 104
        versionName '0.1.4'
    }

    buildTypes {
        release {
            vcsInfo {
                include = false
            }
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        buildConfig = true
    }

    packaging {
        resources {
            excludes += ['/META-INF/{AL2.0,LGPL2.1}']
        }
    }
}
